name: leske_share
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  
  # debug
  device_preview: ^1.1.0

  # presentation
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

  # state mangment
  flutter_riverpod: ^2.3.0
  
  # core
  auto_route: ^5.0.4 # navigation
  fpdart: ^0.5.0 
  equatable: ^2.0.5
  
  get_it: ^7.2.0 # service locator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  
flutter:
  uses-material-design: true

  assets:
    - assets/mockups/